### ISSUE TITLE
Dependency conflict when using ex_webrtc in a new Phoenix project

### ISSUE THREAD

**Issue by filipevarjao** [elixir-webrtc/ex_webrtc#128]
While creating a new phoenix app ` {:phoenix, "~> 1.7.14"}`
Trying to fetch ex_webrtc dependency 
```
Because the lock depends on swoosh 1.16.9 which depends on req ~> 0.5 or ~> 1.0, the lock requires req ~> 0.5 or ~> 1.0.
And because bundlex >= 1.2.0 depends on req ~> 0.4.0, the lock is incompatible with bundlex >= 1.2.0.
And because ex_libsrtp >= 0.7.1 depends on bundlex ~> 1.3, the lock is incompatible with ex_libsrtp >= 0.7.1.
And because every version of ex_webrtc depends on ex_libsrtp ~> 0.7.1, the lock is incompatible with ex_webrtc.
And because your app depends on the lock, no version of ex_webrtc is allowed.
So, because your app depends on ex_webrtc ~> 0.3.0, version solving failed.
```
PS. the project is brain-new, the only dependency added after creating was ex_webrtc.

**Comment by mickel8** [comment]
Thanks for the issue! Looks like the [fix](https://github.com/membraneframework/bundlex/pull/128) in bundlex has already been merged so the only remainign thing is to release its new version.

I will let you know once this happens.

For now, from my experiments, doing `mix deps.update --all --force` should help

**Comment by mickel8** [comment]
Waiting for https://github.com/membraneframework/bundlex/pull/129 to be merged

**Comment by mickel8** [comment]
Bundlex 1.5.2 has been released so now, everything should work correctly. Please reopen if you still encounter any problems! :slightly_smiling_face:
