### ISSUE TITLE
`:missing_rtcp_mux` when streaming to firefox

### ISSUE THREAD

**Issue by Noarkhh** [elixir-webrtc/ex_webrtc#149]
### Environment

firefox version: 129.0
membrane_webrtc_plugin version: 0.21.0
elixir version: 1.17.1
OS: MacOS Sonoma 14.4

### Problem

When trying to stream to a firefox browser using a membrane `Membrane.WebRTC.Sink` element the pipeline crashes with 
```
10:55:43.459 [error] <0.353.0>/:webrtc_output/:webrtc Error occured in Membrane Element:
** (MatchError) no match of right hand side value: {:error, :missing_rtcp_mux}
```

### Reproduction
Run the "MP4 to WebRTC" section in the following livebook: https://github.com/membraneframework-labs/boombox/blob/5f6c646c7b9e755bf03fdc4d1d5dd062cf9b5bb1/examples.livemd

**Comment by LVala** [comment]
It seems like Firefox does not add `rtcp_mux` attribute in rejected m-lines. We're going to take that under consideration.
