### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by srcrip** [elixir-webrtc/ex_webrtc#74]
It would be good to start adding some more examples akin to whats in like https://github.com/pion/webrtc/tree/master/examples

**Comment by LVala** [comment]
Hi, the current amount of examples is enough to understand how the API works and start playing with the library. We'll eventually add more (rewriting the Pion's examples was one of our goals), but now `ex_webrtc` is not mature at all, the API is changing and having to maintain more examples would be a bit of a burden.

tl;dr; when the API becomes stable, we'll add more examples
